//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::comments::Entity as Comments;
pub use super::followers::Entity as Followers;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
